### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by praisethemoon** [chinaran/Compute-file-or-string-md5#1]
Hello!
First of all I would like to thank you for this wonderful hidden gem. I love collecting tiny C libraries that are easily embedded into other source code.

I would like to for the license you would like to expose for your project to check if I can use in my compiler.

Waiting your reply! 
Cheers.

**Comment by chinaran** [comment]
Sorry to reply late.
I have already added Apache License 2.0 to my project, so you can use source code as you want.
I'm glad I could be of some help.
